apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-micro-app
spec:
  selector:
    matchLabels:
      app: go-micro-app
  replicas: 2
  template:
    metadata:
      labels:
        app: go-micro-app
    spec:
      containers:
        - name: "go-micro-sha256-1"
          image: "asia.gcr.io/kube-go-exp/go-micro@sha256:ab67aebae0eb612c565876029a6d9996234862b65c5745334fe772249cd0198d"
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP