apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-micro-app
spec:
  selector:
    matchLabels:
      app: go-micro-app
  replicas: 2
  template:
    metadata:
      labels:
        app: go-micro-app
    spec:
      containers:
        - name: go-micro-app
          image: syrils/go-micro:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP