name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make build

      - name: Staticcheck
        run: |
          # add executables installed with go get to PATH
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
